### ISSUE TITLE
Boot stops with memory alignment issues

### ISSUE THREAD

**Issue by Zubnix** [tombl/linux#2]
Adding a `#define ____cacheline_aligned __attribute__((__aligned__(4)))` in `wasm/include/asm/cache.h` seems to fix this. For some reason wasm doesn't like memory to be 64bytes aligned?

Unfortunately the boot process then fails while bringing up the second CPU. 😢

**Comment by Zubnix** [comment]
latest commits fix this 🥳

**Comment by tombl** [comment]
Yeah thanks for this tip, eventually with the other changes I made it stopped being necessary.
